### ISSUE TITLE
Release v0.9

### ISSUE THREAD

**Issue by adamcaudill** [adamcaudill/yawast#259]
End of month; small release, but time to go out.

## Change Log

* [#20](https://github.com/adamcaudill/yawast/issues/20) - Check for common backup files
* [#207](https://github.com/adamcaudill/yawast/issues/207) - Specify JWT Similar To Cookie
* [#235](https://github.com/adamcaudill/yawast/issues/235) - WordPress Plugin Local Path Disclosure
* [#244](https://github.com/adamcaudill/yawast/issues/244) - Check for common files with phpinfo()
* [#237](https://github.com/adamcaudill/yawast/issues/237) - Bug: Connection error in check_local_ip_disclosure

## Tasks

- [x] Update Change Log
- [x] Test on macOS - @adamcaudill 
- [x] Test on Windows - @brandonlw 
- [x] Tag Release - @adamcaudill 
- [x] Build EXE - @brandonlw 

@brandonlw Can you please test the Windows build to make sure that it’s working properly. I would like to make sure that all of the changes that have been made recently didn't break it. I would like to tag this tonight / tomorrow.

**Comment by adamcaudill** [comment]
@brandonlw I've pushed one last new feature based on a user request; I think this is ready for final testing and release.

**Comment by adamcaudill** [comment]
Done
